#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BethanysPieShopMobile.Resource", IsApplication=true)]

namespace BethanysPieShopMobile
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int bethanyBeige = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int bethanyGreen = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorAccent = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorPrimary = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int colorPrimaryDark = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int ic_launcher_background = 2130771973;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int bethanylogo = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int patternwide = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int aboutButton = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int addToCartButton = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int amountEditText = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int callTextView = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int cartButton = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int cartRecyclerView = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int categoryTextView = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int descriptionTextView = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int emailButton = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int feedbackText = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int googleMapsButton = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int logoImageView = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int map = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int mapsButton = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int orderButton = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int phoneButton = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int pieAmountTextView = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int pieImageView = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int pieMenuRecyclerView = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int pieNameTextView = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int piePager = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int priceTextView = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int shortDescriptionTextView = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int tabsOrderButton = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int textView1 = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int titleTextView = 2130903065;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int about = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int activity_main = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int bethany_map = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int cart = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int cart_viewholder = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int pie_detail = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int pie_menu = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int pie_menu_fragment = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int pie_menu_tabs = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int pie_viewholder = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int second_view = 2130968586;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int ic_launcher = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_launcher_foreground = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher_round = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int action_settings = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int app_name = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppTheme = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int BethanyGreenText = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int BethanysTheme = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
